version: '3.3'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
    - 9411:9411
    deploy:
      mode: replicated
      replicas: 1
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    ports:
    - 9200:9200
    - 9300:9300
    configs:
    - source: elastic_config
      target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: -Xmx256m -Xms256m
      xpack.security.enabled: 'false'
      discovery.type: single-node
    networks:
    - elk
    deploy:
      mode: replicated
      replicas: 1
  logstash:
    image: docker.elastic.co/logstash/logstash:8.1.2
    ports:
    - 5000:5000
    - 9600:9600
    configs:
    - source: logstash_config
      target: /usr/share/logstash/config/logstash.yml
    - source: logstash_pipeline
      target: /usr/share/logstash/pipeline/logstash.conf
    environment:
      LS_JAVA_OPTS: -Xmx256m -Xms256m
      config.string: input { tcp { port => 5000 codec => "json" } } output { elasticsearch { hosts => ["elasticsearch"] index => "micro-%{serviceName}"} }
    networks:
    - elk
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
    - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.2
    ports:
    - 5601:5601
    configs:
    - source: kibana_config
      target: /usr/share/kibana/config/kibana.yml
    networks:
    - elk
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
    - elasticsearch
configs:
  elastic_config:
    file: ./elasticsearch/config/elasticsearch.yml
  logstash_config:
    file: ./logstash/config/logstash.yml
  logstash_pipeline:
    file: ./logstash/pipeline/logstash.conf
  kibana_config:
    file: ./kibana/config/kibana.yml
networks:
  elk:
    driver: bridge